import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { SidebarProvider } from '@/components/ui/sidebar';
import HomeNavbar from '@/components/home-navbar/HomeNavbar';
import HomeSidebar from '@/components/home-navbar/HomeSidebar';
import ProvidersClientSide from './providers';
import { Toaster } from "sonner";

// Required CSS for UploadThing with Tailwind v4
import "uploadthing/tw/v4";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className}`}>
				<ProvidersClientSide>
					<SidebarProvider>
						<div className="w-full relative">
							<HomeNavbar />
							<div className="flex pt-[4rem] h-full max-h-svh max-w-svw">
								<HomeSidebar />
								<main className="w-full">{children}</main>
								<Toaster position="top-center" />
							</div>
						</div>
					</SidebarProvider>
				</ProvidersClientSide>
			</body>
		</html>
	);
}
